swagger: "2.0"
info:
  title: Bank Argent API documentation
  description: Contains all available API endpoints in this codebase
  version: "1.0.0"
  termsOfService: "http://swagger.io/terms/"
host: localhost:3001
basePath: /api/v1
schemes:
  - http

paths:
  /user/login:
    post:
      tags:
        - User Module
      summary: Login
      description: API for Login
      parameters:
        - in: body
          name: body
          description: Login Payload
          required: true
          schema:
            $ref: "#/definitions/Login"
      produces:
        - application/json
      responses:
        "200":
          description: Login Successfully
          schema:
            $ref: "#/definitions/LoginResponse"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error

  /user/signup:
    post:
      tags:
        - User Module
      summary: Signup
      description: API for Signup
      parameters:
        - in: body
          name: body
          description: Signup Payload
          required: true
          schema:
            $ref: "#/definitions/User"
      produces:
        - application/json
      responses:
        "200":
          description: Signup Successfully
          schema:
            $ref: "#/definitions/ApiResponse"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error

  /user/profile:
    post:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for fetching a user profile
      responses:
        "200":
          description: User profile retrieved successully
          schema:
            $ref: "#/definitions/ApiResponse"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error
    put:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for updating a user profile
      parameters:
        - in: body
          name: body
          description: Update user profile attributes
          required: true
          schema:
            $ref: "#/definitions/UserProfile"
        - in: header
          name: token
          description: Bearer Token
          required: true
          type: string
      produces:
        - application/json
      responses:
        "200":
          description: User profile retrieved successully
          schema:
            $ref: "#/definitions/ApiResponse"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error

  /user/accounts:
    get:
      security:
        - Bearer: []
      tags:
        - Transaction Module
      summary: User Account API
      description: API for retrieving all user account
      parameters:
        - in: header
          name: token
          description: Bearer Token
          required: true
          type: string
      produces:
        - application/json
      responses:
        "200":
          description: The transactions have been successfully retrieved.
          schema:
            type: array
            items: { $ref: "#/definitions/UserAccount" }
        "400":
          description: Invalid Fields
        "401":
          description: Unauthorized
        "500":
          description: Internal Server Error

  /user/{account_id}/transactions:
    get:
      security:
        - Bearer: []
      tags:
        - Transaction Module
      summary: User Account API
      description: API for retrieving user transactions
      parameters:
        - in: header
          name: token
          description: Bearer Token
          required: true
          type: string
        - in: path
          name: account_id
          description: ID of the Account
          required: true
          type: string
        - in: query
          name: month
          description: Filter transactions for a specific month (2024-05)
          required: true
          type: string
      produces:
        - application/json
      responses:
        "200":
          description: The transactions have been successfully retrieved.
          schema:
            type: array
            items: { $ref: "#/definitions/UserTransaction" }
        "400":
          description: Invalid Fields
        "401":
          description: Unauthorized
        "404":
          description: Not Found
        "500":
          description: Internal Server Error

  /user/{account_id}/transactions/{transaction_id}:
    get:
      security:
        - Bearer: []
      tags:
        - Transaction Module
      summary: User Transaction API
      description: API for retrieving a user transaction
      parameters:
        - in: path
          name: account_id
          description: ID Account
          required: true
          type: string
        - in: path
          name: transaction_id
          description: ID of the transaction to be updated
          required: true
          type: string
        - in: header
          name: token
          description: Bearer Token
          required: true
          type: string
      produces:
        - application/json
      responses:
        "200":
          description: The transactions have been successfully retrieved.
          schema:
            $ref: "#/definitions/UserTransaction"
        "400":
          description: Invalid Fields
        "401":
          description: Unauthorized
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
    put:
      security:
        - Bearer: []
      tags:
        - Transaction Module
      summary: User Transaction API
      description: API for updating a transaction
      parameters:
        - in: path
          name: account_id
          description: ID of the user account
          required: true
          type: string
        - in: path
          name: transaction_id
          description: ID of the transaction to update
          required: true
          type: string
        - in: header
          name: token
          description: Bearer Token
          required: true
          type: string
        - in: body
          name: body
          description: Update Transaction attributes
          required: true
          schema:
            $ref: "#/definitions/UpdateTransaction"
      produces:
        - application/json
      responses:
        "200":
          description: Transaction updated
          schema:
            $ref: "#/definitions/UpdateTransaction"
        "400":
          description: Invalid Fields
        "401":
          description: Unauthorized
        "404":
          description: Not Found
        "500":
          description: Internal Server Error

securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header

definitions:
  User:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
      firstName:
        type: string
        description: user first name
      lastName:
        type: string
        description: user last name
      userName:
        type: string
        description: user public name
  Login:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
  ApiResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          id:
            type: string
          email:
            type: string
  LoginResponse:
    type: object
    properties:
      token:
        type: string
  UserProfile:
    type: object
    properties:
      userName:
        type: string
  UserAccount:
    type: object
    properties:
      account_id:
        type: string
      balance:
        type: number
        format: float
    required:
      - account_id
      - balance
    example:
      account_id: "123456"
      balance: 1000.50
  UserTransaction:
    type: object
    properties:
      transaction_id:
        type: string
      date:
        type: string
        format: date
      description:
        type: object
        properties:
          transaction_type:
            type: string
          category:
            type: string
          note:
            type: string
      amount:
        type: number
        format: float
      balance:
        type: number
        format: float
  UpdateTransaction:
    type: object
    properties:
      transaction_type:
        type: string
        description: Type of transaction (non-editable)
      category:
        type: string
      note:
        type: string